# Generated by Django 5.2.5 on 2025-11-19 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='equipos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_limite_inscripcion', models.DateTimeField()),
                ('fecha_inicio', models.DateField()),
                ('cupos_totales', models.PositiveIntegerField(default=16)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto para Inscripción'), ('EN_JUEGO', 'En Juego'), ('FINALIZADO', 'Finalizado')], default='ABIERTO', max_length=10)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.division')),
                ('equipos_inscritos', models.ManyToManyField(related_name='torneos', through='torneos.Inscripcion', to='equipos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('GRUPOS', 'Fase de Grupos'), ('OCTAVOS', 'Octavos de Final'), ('CUARTOS', 'Cuartos de Final'), ('SEMIFINAL', 'Semifinal'), ('FINAL', 'Final')], max_length=10)),
                ('resultado_local', models.PositiveIntegerField(default=0)),
                ('resultado_visitante', models.PositiveIntegerField(default=0)),
                ('equipo_local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_local', to='equipos.equipo')),
                ('equipo_visitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_visitante', to='equipos.equipo')),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_ganados', to='equipos.equipo')),
                ('partido_siguiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partido_anterior', to='torneos.partido')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='torneos.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='torneos.torneo'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('torneo', 'equipo')},
        ),
    ]
