# Generated by Django 5.2.5 on 2025-11-20 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='sets_local',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='partido',
            name='sets_visitante',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='torneo',
            name='equipos_por_grupo',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('equipos_en_grupo', models.ManyToManyField(related_name='grupos_participados', to='equipos.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='torneos.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='torneos.grupo'),
        ),
    ]
