# Generated by Django 5.2.5 on 2025-11-20 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_equipo_division_alter_equipo_nombre'),
        ('torneos', '0002_partido_sets_local_partido_sets_visitante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_jugados', models.PositiveSmallIntegerField(default=0)),
                ('partidos_ganados', models.PositiveSmallIntegerField(default=0)),
                ('partidos_perdidos', models.PositiveSmallIntegerField(default=0)),
                ('sets_a_favor', models.PositiveSmallIntegerField(default=0)),
                ('sets_en_contra', models.PositiveSmallIntegerField(default=0)),
                ('games_a_favor', models.PositiveSmallIntegerField(default=0)),
                ('games_en_contra', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-partidos_ganados', '-sets_a_favor', 'sets_en_contra'],
            },
        ),
        migrations.CreateModel(
            name='PartidoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e1_set1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('e2_set1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('e1_set2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('e2_set2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('e1_set3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('e2_set3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('e1_sets_ganados', models.PositiveSmallIntegerField(default=0)),
                ('e2_sets_ganados', models.PositiveSmallIntegerField(default=0)),
                ('e1_games_ganados', models.PositiveSmallIntegerField(default=0)),
                ('e2_games_ganados', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['ronda', 'orden_partido']},
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='equipos_en_grupo',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='equipo_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='equipo_visitante',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='partido_siguiente',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='resultado_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='resultado_visitante',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='sets_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='sets_visitante',
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_bracket_e1', to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_bracket_e2', to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='orden_partido',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partido',
            name='resultado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='ronda',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partido',
            name='siguiente_partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_previos', to='torneos.partido'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='ganador_del_torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneos_ganados', to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='tipo_torneo',
            field=models.CharField(choices=[('E', 'Eliminación Directa'), ('G', 'Fase de Grupos + Eliminatoria')], default='G', max_length=1),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partido',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_bracket_ganados', to='equipos.equipo'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='equipos_inscritos',
            field=models.ManyToManyField(related_name='torneos_participados', through='torneos.Inscripcion', to='equipos.equipo'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='estado',
            field=models.CharField(choices=[('AB', 'Inscripción Abierta'), ('EJ', 'En Juego'), ('FN', 'Finalizado')], default='AB', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('equipo', 'torneo'), name='inscripcion_unica'),
        ),
        migrations.AddField(
            model_name='equipogrupo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='equipogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabla', to='torneos.grupo'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='equipos',
            field=models.ManyToManyField(related_name='grupos_asignados', through='torneos.EquipoGrupo', to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='partidogrupo',
            name='equipo1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_grupo_e1', to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='partidogrupo',
            name='equipo2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_grupo_e2', to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='partidogrupo',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='partidogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_grupo', to='torneos.grupo'),
        ),
    ]
