# Generated by Django 5.2.5 on 2025-11-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0003_equipogrupo_partidogrupo_alter_partido_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='sets_local',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='partido',
            name='sets_visitante',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
