# Generated by Django 5.2.5 on 2025-11-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0004_partido_sets_local_partido_sets_visitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipogrupo',
            name='numero',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
