# Generated by Django 5.2.8 on 2025-11-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_equipo_division_alter_equipo_nombre'),
        ('torneos', '0005_equipogrupo_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partidogrupo',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partidogrupo',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_grupo_ganados', to='equipos.equipo'),
        ),
    ]
