# Generated by Django 5.2.8 on 2026-02-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0007_torneo_division_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='categoria',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Mixto')], default='X', help_text='Categoría del torneo (Masculino, Femenino, Mixto)', max_length=1),
        ),
    ]
