# Generated by Django 5.2.8 on 2026-02-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0008_torneo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='equipos_por_grupo',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
