# Generated by Django 5.2.8 on 2026-02-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0009_alter_torneo_equipos_por_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='forzar_grupos_de_3',
            field=models.BooleanField(default=False, help_text='Si se activa, el sistema exigirá que el total de equipos sea divisible por 3.'),
        ),
    ]
