# Generated by Django 5.2.8 on 2026-02-18 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0010_torneo_forzar_grupos_de_3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='organizador',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'ORGANIZER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='torneos_organizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
