# Generated by Django 5.2.8 on 2026-02-18 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organizacion_remove_sponsor_organizador_and_more'),
        ('torneos', '0011_torneo_organizador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='organizador',
        ),
        migrations.AddField(
            model_name='torneo',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='torneos', to='accounts.organizacion'),
        ),
    ]
