# Generated by Django 5.2.8 on 2026-02-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0012_remove_torneo_organizador_torneo_organizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='placeholder_e1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='placeholder_e2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
