# Generated by Django 5.2.8 on 2026-02-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0013_partido_placeholder_e1_partido_placeholder_e2'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='fecha_inicio_default',
            field=models.DateField(blank=True, help_text='Fecha predeterminada para los partidos de este grupo', null=True),
        ),
    ]
