# Generated by Django 5.2.8 on 2026-02-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0014_grupo_fecha_inicio_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='foto_campeones',
            field=models.ImageField(blank=True, help_text='Opcional: Sube la foto del equipo ganador al finalizar el torneo. La imagen se mostrará en los detalles de la competencia.', null=True, upload_to='torneos/campeones/'),
        ),
    ]
