# Generated by Django 5.2.8 on 2026-05-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0015_torneo_foto_campeones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipogrupo',
            options={'ordering': ['-prioridad_llave', '-partidos_ganados', '-sets_a_favor', 'sets_en_contra']},
        ),
        migrations.AddField(
            model_name='equipogrupo',
            name='prioridad_llave',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='torneo',
            name='formato_grupos_4',
            field=models.CharField(choices=[('RR', 'Todos contra todos (3 partidos)'), ('LL', 'Llaves internas (2 rondas, Ganadores/Perdedores)')], default='RR', help_text='Formato de juego para las zonas de 4 parejas.', max_length=2),
        ),
    ]
