# Generated by Django 5.2.8 on 2026-05-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0016_alter_equipogrupo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipogrupo',
            options={'ordering': ['-partidos_ganados', '-diferencia_sets', '-diferencia_games']},
        ),
        migrations.RemoveField(
            model_name='equipogrupo',
            name='prioridad_llave',
        ),
        migrations.AddField(
            model_name='equipogrupo',
            name='diferencia_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipogrupo',
            name='diferencia_sets',
            field=models.IntegerField(default=0),
        ),
    ]
