# Generated by Django 5.2.8 on 2026-05-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0017_alter_equipogrupo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad/localidad de la sede.', max_length=100),
        ),
        migrations.AddField(
            model_name='torneo',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagen de portada del torneo (banner).', null=True, upload_to='torneos/portadas/'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='premio',
            field=models.CharField(blank=True, help_text='Ej: Trofeos + $100.000 + indumentaria.', max_length=255),
        ),
        migrations.AddField(
            model_name='torneo',
            name='reglamento',
            field=models.TextField(blank=True, help_text='Reglas del torneo (texto libre).'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='sede_direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='torneo',
            name='sede_nombre',
            field=models.CharField(blank=True, help_text='Nombre del club o sede.', max_length=150),
        ),
    ]
