# Generated by Django 5.2.8 on 2026-05-30 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_organizacion_whatsapp'),
        ('torneos', '0018_torneo_ciudad_torneo_cover_image_torneo_premio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('cupos_ascenso', models.PositiveSmallIntegerField(default=0, help_text='Cuántos primeros del circuito ascienden de categoría (0 = sin ascensos).')),
                ('cupos_descenso', models.PositiveSmallIntegerField(default=0, help_text='Cuántos últimos descienden de categoría (0 = sin descensos).')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuitos', to='accounts.organizacion')),
                ('torneos', models.ManyToManyField(blank=True, related_name='circuitos', to='torneos.torneo')),
            ],
            options={
                'verbose_name': 'Circuito',
                'verbose_name_plural': 'Circuitos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
