# Generated by Django 5.2.8 on 2026-05-30 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_organizacion_whatsapp'),
        ('torneos', '0019_circuito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Americano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('A', 'Americano (rotación fija)'), ('M', 'Mexicano (por ranking)')], default='A', max_length=1)),
                ('num_canchas', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('IN', 'Inscripción abierta'), ('EJ', 'En juego'), ('FN', 'Finalizado')], default='IN', max_length=2)),
                ('codigo', models.CharField(blank=True, help_text='Código para el link de inscripción.', max_length=8, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='americanos', to='accounts.organizacion')),
            ],
            options={
                'verbose_name': 'Americano/Mexicano',
                'verbose_name_plural': 'Americanos/Mexicanos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='JugadorAmericano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntos', models.IntegerField(default=0)),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('americano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='torneos.americano')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones_americano', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-puntos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RondaAmericano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('americano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='torneos.americano')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='PartidoAmericano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancha', models.PositiveSmallIntegerField(default=1)),
                ('games_a', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('games_b', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cargado', models.BooleanField(default=False)),
                ('a1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='torneos.jugadoramericano')),
                ('a2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='torneos.jugadoramericano')),
                ('b1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='torneos.jugadoramericano')),
                ('b2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='torneos.jugadoramericano')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='torneos.rondaamericano')),
            ],
            options={
                'ordering': ['ronda__numero', 'cancha'],
            },
        ),
    ]
