# Generated by Django 5.2.8 on 2026-06-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0020_americano_jugadoramericano_rondaamericano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='resolucion',
            field=models.CharField(choices=[('N', 'Normal'), ('W', 'Walkover (no se presentó)'), ('A', 'Abandono (se retiró)')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='partidogrupo',
            name='resolucion',
            field=models.CharField(choices=[('N', 'Normal'), ('W', 'Walkover (no se presentó)'), ('A', 'Abandono (se retiró)')], default='N', max_length=1),
        ),
    ]
