# Generated by Django 5.2.8 on 2026-06-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0021_partido_resolucion_partidogrupo_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='estructura_manual',
            field=models.BooleanField(default=False),
        ),
    ]
