# Generated by Django 5.2.8 on 2026-06-13 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_pushsubscription'),
        ('torneos', '0022_torneo_estructura_manual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('sizes', models.JSONField(default=list)),
                ('clasifican_por_grupo', models.PositiveSmallIntegerField(default=2, help_text='Cuántas parejas pasan de cada zona a la fase final.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_creados', to=settings.AUTH_USER_MODEL)),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formatos', to='accounts.organizacion')),
            ],
            options={
                'verbose_name': 'Formato personalizado',
                'verbose_name_plural': 'Formatos personalizados',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='torneo',
            name='formato_personalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneos', to='torneos.formatopersonalizado'),
        ),
    ]
