# Generated by Django 5.2.8 on 2026-06-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0023_formatopersonalizado_torneo_formato_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatopersonalizado',
            name='cruces_manuales',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
