# Generated by Django 5.2.8 on 2026-08-03 22:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0024_formatopersonalizado_cruces_manuales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagen de portada del torneo (banner).', null=True, upload_to='torneos/portadas/', validators=[core.validators.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='foto_campeones',
            field=models.ImageField(blank=True, help_text='Opcional: Sube la foto del equipo ganador al finalizar el torneo. La imagen se mostrará en los detalles de la competencia.', null=True, upload_to='torneos/campeones/', validators=[core.validators.validar_imagen]),
        ),
    ]
