# Generated by Django 5.2.8 on 2026-08-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_customuser_options_and_more'),
        ('equipos', '0009_busquedacompanero'),
        ('torneos', '0025_alter_torneo_cover_image_alter_torneo_foto_campeones'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='partido',
            index=models.Index(fields=['torneo', 'ronda', 'orden_partido'], name='partido_torneo_ronda_idx'),
        ),
        migrations.AddIndex(
            model_name='partidogrupo',
            index=models.Index(fields=['grupo', 'ganador'], name='pgrupo_grupo_ganador_idx'),
        ),
        migrations.AddIndex(
            model_name='torneo',
            index=models.Index(fields=['estado', 'fecha_inicio'], name='torneo_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='torneo',
            index=models.Index(fields=['ciudad'], name='torneo_ciudad_idx'),
        ),
        migrations.AddIndex(
            model_name='torneo',
            index=models.Index(fields=['organizacion', 'estado'], name='torneo_org_estado_idx'),
        ),
    ]
