# Generated by Django 5.2.16 on 2026-08-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0026_partido_partido_torneo_ronda_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='instrucciones_pago',
            field=models.TextField(blank=True, help_text='Opcional: fecha límite, formas de pago, lo que quieras aclarar.', verbose_name='Aclaraciones sobre el pago'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='precio_inscripcion',
            field=models.PositiveIntegerField(blank=True, help_text='En pesos, sin centavos. Dejalo vacío si el torneo es gratis o cobrás aparte.', null=True, verbose_name='Precio de la inscripción (por pareja)'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='senia',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Ej: la mitad de la inscripción.', null=True, verbose_name='Seña para reservar el lugar'),
        ),
    ]
