# Generated by Django 5.2.16 on 2026-08-04 01:53

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0009_busquedacompanero'),
        ('torneos', '0027_torneo_instrucciones_pago_torneo_precio_inscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/', validators=[core.validators.validar_imagen], verbose_name='Comprobante de transferencia'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estado_pago',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('SE', 'Señado'), ('PA', 'Pagado'), ('EX', 'Exento')], default='PE', max_length=2, verbose_name='Estado del pago'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='monto_pagado',
            field=models.PositiveIntegerField(blank=True, help_text='Cuánto pagó realmente la pareja, en pesos.', null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nota_pago',
            field=models.CharField(blank=True, help_text="Uso interno del organizador. Ej: 'pagó solo Juan'.", max_length=200),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['torneo', 'estado_pago'], name='insc_torneo_pago_idx'),
        ),
    ]
