# Generated by Django 5.2.16 on 2026-08-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0028_inscripcion_comprobante_inscripcion_estado_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='recordatorios_enviados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='partidogrupo',
            name='recordatorios_enviados',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
