# Generated by Django 5.2.8 on 2026-03-20 01:28

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        UnaccentExtension(),
    ]
