# Generated by Django 5.2.8 on 2026-08-03 22:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='testimonios/', validators=[core.validators.validar_imagen]),
        ),
    ]
