# Generated by Django 5.2.5 on 2025-11-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'un usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
