# Generated by Django 5.2.8 on 2026-02-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_division_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
