# Generated by Django 5.2.8 on 2026-02-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_verified_customuser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('PLAYER', 'Jugador'), ('ADMIN', 'Admin'), ('ORGANIZER', 'Organizador')], default='PLAYER', max_length=10),
        ),
    ]
