# Generated by Django 5.2.8 on 2026-02-18 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizadorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del organizador o sede.')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizadores/logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_organizador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='sponsors/')),
                ('link', models.URLField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el carrusel')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='accounts.organizadorprofile')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
