# Generated by Django 5.2.8 on 2026-02-18 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organizadorprofile_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Default Org', max_length=150, unique=True)),
                ('alias', models.SlugField(default='default-org', help_text='URL amigable (ej: club-padel-mdq)', max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del organizador o sede.')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizadores/logos/')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='organizador',
        ),
        migrations.AddField(
            model_name='customuser',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='accounts.organizacion'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='accounts.organizacion'),
        ),
        migrations.DeleteModel(
            name='OrganizadorProfile',
        ),
    ]
