# Generated by Django 5.2.8 on 2026-02-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organizacion_remove_sponsor_organizador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='alias',
            field=models.SlugField(help_text='URL amigable (ej: club-padel-mdq)', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
