# Generated by Django 5.2.8 on 2026-02-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_organizacion_alias_alter_organizacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_dummy',
            field=models.BooleanField(default=False, help_text='Indica si el usuario fue creado por un organizador para usar de relleno y no tiene cuenta real.', verbose_name='Es Jugador Creado por Organizador'),
        ),
    ]
