# Generated by Django 5.2.8 on 2026-05-11 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_genero_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='receptor_notificaciones',
            field=models.ForeignKey(blank=True, help_text='Organizador que recibirá los emails de nuevas inscripciones.', limit_choices_to={'tipo_usuario': 'ORGANIZER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizacion_notificaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
