# Generated by Django 5.2.8 on 2026-05-30 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_organizacion_receptor_notificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp de contacto en formato internacional (ej: +54911...). Habilita el botón de contacto.', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{8,15}$', 'Ingresá el número en formato internacional, solo dígitos (ej: +5491123456789).')]),
        ),
    ]
