# Generated by Django 5.2.8 on 2026-06-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_organizacion_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad/localidad de la sede.', max_length=100),
        ),
    ]
