# Generated by Django 5.2.8 on 2026-06-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_organizacion_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='club',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, help_text='Usuario de Instagram, sin @', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='juega_desde',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Año en que empezó a jugar', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mano_habil',
            field=models.CharField(blank=True, choices=[('D', 'Diestra'), ('Z', 'Zurda')], max_length=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='posicion_cancha',
            field=models.CharField(blank=True, choices=[('D', 'Drive'), ('R', 'Revés'), ('A', 'Ambas')], max_length=1),
        ),
    ]
