# Generated by Django 5.2.8 on 2026-06-02 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_merged_into'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('source_id', models.IntegerField()),
                ('source_email', models.CharField(blank=True, max_length=254)),
                ('source_nombre', models.CharField(blank=True, max_length=210)),
                ('source_was_dummy', models.BooleanField(default=False)),
                ('target_email', models.CharField(blank=True, max_length=254)),
                ('target_nombre', models.CharField(blank=True, max_length=210)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusiones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusiones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de fusión',
                'verbose_name_plural': 'Registros de fusión',
                'ordering': ['-created_at'],
            },
        ),
    ]
