# Generated by Django 5.2.8 on 2026-08-03 22:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', validators=[core.validators.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizadores/logos/', validators=[core.validators.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='imagen',
            field=models.ImageField(upload_to='sponsors/', validators=[core.validators.validar_imagen]),
        ),
    ]
