# Generated by Django 5.2.8 on 2026-08-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customuser_imagen_alter_organizacion_logo_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['tipo_usuario', 'is_dummy'], name='user_tipo_dummy_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['division', 'tipo_usuario'], name='user_division_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['organizacion'], name='user_organizacion_idx'),
        ),
    ]
