# Generated by Django 5.2.16 on 2026-08-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='alias_cobro',
            field=models.CharField(blank=True, help_text='Ej: miclub.padel. Se muestra a los jugadores al inscribirse.', max_length=100, verbose_name='Alias o CBU para transferencias'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='titular_cobro',
            field=models.CharField(blank=True, help_text='Nombre que figura en la cuenta, para que el jugador verifique antes de transferir.', max_length=150, verbose_name='Titular de la cuenta'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='whatsapps_comprobante',
            field=models.CharField(blank=True, help_text='Uno o varios separados por coma. Ej: +5492235937115, +5492236337881', max_length=200, verbose_name='WhatsApp(s) para enviar el comprobante'),
        ),
    ]
