# Generated by Django 5.2.16 on 2026-08-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_organizacion_alias_cobro_organizacion_titular_cobro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Se activa en las cuentas creadas con contraseña automática.', verbose_name='Tiene que cambiar la contraseña al entrar'),
        ),
    ]
