# Generated by Django 5.2.5 on 2025-11-19 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(editable=False, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.division')),
                ('jugador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_como_jugador1', to=settings.AUTH_USER_MODEL)),
                ('jugador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_como_jugador2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('jugador1', 'jugador2')},
            },
        ),
    ]
