# Generated by Django 5.2.5 on 2025-11-20 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options'),
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.division'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
