# Generated by Django 5.2.8 on 2026-02-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Mixto')], default='X', max_length=1, verbose_name='Categoría del Equipo'),
        ),
    ]
