# Generated by Django 5.2.8 on 2026-02-18 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_equipo_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='es_dummy',
            field=models.BooleanField(default=False, help_text='Equipo creado automáticamente para rellenar grupos.', verbose_name='Es Pareja Libre (Dummy)'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='jugador1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos_como_jugador1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='jugador2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos_como_jugador2', to=settings.AUTH_USER_MODEL),
        ),
    ]
