# Generated by Django 5.2.8 on 2026-02-18 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_organizacion_alias_alter_organizacion_nombre'),
        ('equipos', '0005_equipo_es_dummy_alter_equipo_jugador1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.division'),
        ),
    ]
