# Generated by Django 5.2.8 on 2026-02-26 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_is_dummy'),
        ('equipos', '0006_alter_equipo_division'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('torneos_ganados', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings_equipos_division', to='accounts.division')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings_equipo', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Ranking de Equipo',
                'verbose_name_plural': 'Rankings de Equipos',
                'constraints': [models.UniqueConstraint(fields=('equipo', 'division'), name='unique_ranking_equipo_division')],
            },
        ),
        migrations.CreateModel(
            name='RankingJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('torneos_ganados', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings_jugadores_division', to='accounts.division')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings_jugador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ranking de Jugador',
                'verbose_name_plural': 'Rankings de Jugadores',
                'constraints': [models.UniqueConstraint(fields=('jugador', 'division'), name='unique_ranking_jugador_division')],
            },
        ),
    ]
