# Generated by Django 5.2.8 on 2026-04-10 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_genero_default'),
        ('equipos', '0007_rankingequipo_rankingjugador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='equipo',
            name='esta_activo',
            field=models.BooleanField(default=True, verbose_name='Esta Activo'),
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(condition=models.Q(('esta_activo', True)), fields=('jugador1', 'jugador2'), name='unique_active_team'),
        ),
        migrations.DeleteModel(
            name='RankingEquipo',
        ),
    ]
