# Generated by Django 5.2.8 on 2026-05-30 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_organizacion_whatsapp'),
        ('equipos', '0008_remove_rankingequipo_division_and_more'),
        ('torneos', '0018_torneo_ciudad_torneo_cover_image_torneo_premio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaCompanero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('nota', models.TextField(blank=True, help_text='Contanos qué buscás (nivel, disponibilidad, etc.)')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='busquedas', to='accounts.division')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busquedas_companero', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='busquedas_companero', to='torneos.torneo')),
            ],
            options={
                'verbose_name': 'Búsqueda de compañero',
                'verbose_name_plural': 'Búsquedas de compañero',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
